version: 2

models:
  # Customers
  - name: silver_olist_customers_dataset
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: customer_unique_id
        tests:
          - not_null
      - name: customer_zip_code_prefix
        tests:
          - not_null
      - name: customer_city
        tests:
          - not_null
      - name: customer_state
        tests:
          - not_null
          - accepted_values:
              # Sử dụng danh sách mã viết tắt cho các bang của Brazil
              values: [
                "SC", "RS", "DF", "MG", "RN", "SP", "GO", "AM", "PA", "PE", "PB",
                "AP", "ES", "TO", "MT", "RR", "PI", "PR", "CE", "BA", "AC", "RJ",
                "MA", "AL", "RO", "SE", "MS"
              ]

  # Sellers
  - name: silver_olist_sellers_dataset 
    columns:
      - name: seller_id
        tests:
          - unique
          - not_null
      - name: seller_zip_code_prefix
        tests:
          - not_null
      - name: seller_city
        tests:
          - not_null
      - name: seller_state
        tests:
          - not_null
          - accepted_values:
              # Đảm bảo thống nhất với customer_state (sử dụng mã viết tắt)
              values: [
                "SC", "RS", "DF", "MG", "RN", "SP", "GO", "AM", "PA", "PE", "PB",
                "AP", "ES", "TO", "MT", "RR", "PI", "PR", "CE", "BA", "AC", "RJ",
                "MA", "AL", "RO", "SE", "MS", "RIO GRANDE DO SUL", "RIO DE JANEIRO"
              ]

  # Products
  - name: silver_olist_products_dataset
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
      - name: product_category_name
        tests:
          - not_null
          - relationships:
              to: ref('silver_product_category_name_translation')
              field: product_category_name
              config:
                severity: warn
    
  # Product Category Translation
  - name: silver_product_category_name_translation
    columns:
      - name: product_category_name
        tests:
          - unique
          - not_null
      - name: product_category_name_english
        tests:
          - not_null
          - unique

  # Orders
  - name: silver_olist_orders_dataset
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('silver_olist_customers_dataset')
              field: customer_id
      - name: order_status
        tests:
          - not_null
          - accepted_values:
              values: ['delivered', 'shipped', 'canceled', 'unavailable', 'processing', 'invoiced', 'created', 'approved']
      - name: order_purchase_timestamp
        tests:
          - not_null
      #- name: order_approved_at
      #  tests: 
      #    - not_null

  # Order Items
  - name: silver_olist_order_items_dataset
    columns:
      - name: order_id
        tests:
          - not_null
          - relationships:
              to: ref('silver_olist_orders_dataset')
              field: order_id
      - name: order_item_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
          - relationships:
              to: ref('silver_olist_products_dataset')
              field: product_id
      - name: seller_id
        tests:
          - not_null
          - relationships:
              to: ref('silver_olist_sellers_dataset')
              field: seller_id
      - name: shipping_limit_date
        tests:
          - not_null
      - name: price
        tests:
          - not_null
      - name: freight_value
        tests:
          - not_null

  # Order Payments
  - name: silver_olist_order_payments_dataset
    columns:
      - name: order_id
        tests:
          - not_null
          - relationships:
              to: ref('silver_olist_orders_dataset')
              field: order_id
      - name: payment_type
        tests:
          - not_null
          - accepted_values:
              values: ["credit_card", "boleto", "voucher", "debit_card", "not_defined"]

  # Order Reviews
  - name: silver_olist_order_reviews_dataset
    columns:
      - name: review_id
        tests:
          - unique
          - not_null
      - name: order_id
        tests:
          - not_null
          - relationships:
              to: ref('silver_olist_orders_dataset')
              field: order_id
      - name: review_score
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5]
      - name: review_comment_title
        tests: []  # Có thể NULL
      - name: review_comment_message
        tests: []  # Có thể NULL